"KsAcademyHeadcountGridRow2aCell1Dropbox_init": >
  {"MDX":"
     SELECT
           {[Measure Headcount].[Measure Headcount].[Value]}
          ON COLUMNS ,
           {TM1SUBSETALL([Organization Unit].[Organization Unit])}
          ON ROWS
        FROM [Headcount]
        WHERE
          (
           [Period].[Period].[2024],
           [Version].[Version].[Actual],
           [Lineitem Headcount].[Lineitem Headcount].[Total Cost],
           [Employee].[Employee].[Employee 1]
          )
     "}


"KsAcademyHeadcountGridTable_init": >
  {"MDX":"
        WITH
        SET [Employee:Employee:}rollup_1] AS {[Employee].[Employee].[Employee 1],[Employee].[Employee].[Employee 2],[Employee].[Employee].[Employee 3],[Employee].[Employee].[Employee 4],[Employee].[Employee].[Employee 5],[Employee].[Employee].[Employee 6],[Employee].[Employee].[Employee 7],[Employee].[Employee].[Employee 8],[Employee].[Employee].[Employee 9]}
        MEMBER [Employee].[Employee].[}rollup_1] AS AGGREGATE({[Employee:Employee:}rollup_1]})
        SELECT
           {[Lineitem Headcount].[Lineitem Headcount].[Base Salary],[Lineitem Headcount].[Lineitem Headcount].[FTE],[Lineitem Headcount].[Lineitem Headcount].[Bonus]}
          ON COLUMNS ,
           {[Organization Unit].[Organization Unit].[Business Unit 1],[Organization Unit].[Organization Unit].[Business Unit 2],[Organization Unit].[Organization Unit].[Business Unit 3],[Organization Unit].[Organization Unit].[Business Unit 4],[Organization Unit].[Organization Unit].[Business Unit 5]}
          ON ROWS
        FROM [Headcount]
        WHERE
          (
           [Version].[Version].[Actual],
           [Period].[Period].[$year],
           [Measure Headcount].[Measure Headcount].[$value],
           [Employee].[Employee].[}rollup_1]
          )
   "}


"BusinessUnitGridTable_delta_init": >
  {"MDX":"
     SELECT {DRILLDOWNMEMBER({StrToSet(\"{[Period].[Period].[$year]}\")},
     {[Period].[Period].[$year]})} ON COLUMNS, {StrToSet(\"{[Employee].[Employee].[BU$number]}\")}
     ON ROWS FROM [Headcount] WHERE ([Version].[Version].[Forecast], [Organization Unit].[Organization Unit].[$unit],
     [Lineitem Headcount].[Lineitem Headcount].[FTE], [Measure Headcount].[Measure Headcount].[$value])
   "}
"BusinessUnitGridTable_init": >
  {"MDX":"
     SELECT {DRILLDOWNMEMBER({StrToSet(\"{[Period].[Period].[$year]}\")},
     {[Period].[Period].[$year]})} ON COLUMNS,NON EMPTY {StrToSet(\"{[Employee].[Employee].[BU$number]}\")}
     ON ROWS FROM [Headcount] WHERE ([Version].[Version].[Forecast], [Organization Unit].[Organization Unit].[$unit],
     [Lineitem Headcount].[Lineitem Headcount].[FTE], [Measure Headcount].[Measure Headcount].[$value])
   "}
"BusinessUnitGridTable_write": >
  {
           "Parameters": [
                {"Name": "pEmployee", "Value": "$employee"},
                {"Name": "pOrgUnit", "Value": "$unit"},
                {"Name": "pPeriod", "Value": "$period"},
                {"Name": "pValue", "Value": "$value"}
           ]
       }


"reusableGlobalCompanyPopupGridTable_init": >
  {"MDX":"
          With Member [}ElementAttributes_Organization Unit].[UI Name] as
              iif ([Organization Unit].[Organization Unit].CurrentMember.Properties('Country')<>'',
                  [Organization Unit].[Organization Unit].CurrentMember.Properties('Country'),
                  [Organization Unit].[Organization Unit].CurrentMember.Name)
            SELECT
               {[}ElementAttributes_Organization Unit].[UI Name]}
              ON COLUMNS ,
               {[Organization Unit].[Organization Unit].Members}
              ON ROWS
            FROM [}ElementAttributes_Organization Unit]
   "}


"reusableVersionPopupDropbox_init": >
  {"MDX":"
          With Member [}ElementAttributes_Version].[UI Name] as
              iif ([Version].[Version].CurrentMember.Properties('Country')<>'',
                  [Version].[Version].CurrentMember.Properties('Country'),
                  [Version].[Version].CurrentMember.Name)
            SELECT
               {[}ElementAttributes_Version].[UI Name]}
              ON COLUMNS ,
               {[Version].[Version].Members}
              ON ROWS
            FROM [}ElementAttributes_Version]
   "}


